
# parsetabhtml.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "'{\xe9'\xf5j\xfe`\x87\xc3&=o\xb5P\x96"
    
_lr_action_items = {'LANGLE':([0,2,3,4,5,7,16,17,23,],[1,-3,-5,-13,-4,1,-8,1,-9,]),'WORD':([0,1,2,3,4,5,7,8,9,11,16,17,18,20,23,],[2,8,-3,-5,-13,-4,2,-6,12,12,-8,2,-12,21,-9,]),'STRING':([0,2,3,4,5,7,15,16,17,23,],[3,-3,-5,-13,-4,3,18,-8,3,-9,]),'JAVASCRIPT':([0,2,3,4,5,7,16,17,23,],[4,-3,-5,-13,-4,4,-8,4,-9,]),'EQUAL':([0,2,3,4,5,7,12,16,17,23,],[5,-3,-5,-13,-4,5,15,-8,5,-9,]),'SLASHRANGLE':([8,9,11,13,14,18,],[-6,-10,-10,16,-11,-12,]),'RANGLE':([8,9,11,13,14,18,21,22,],[-6,-10,-10,17,-11,-12,-7,23,]),'LANGLESLASH':([2,3,4,5,7,10,16,17,19,23,],[-3,-5,-13,-4,-2,-1,-8,-2,20,-9,]),'$end':([0,2,3,4,5,6,7,10,16,23,],[-2,-3,-5,-13,-4,0,-2,-1,-8,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tagarg':([9,11,],[11,11,]),'tagnameend':([20,],[22,]),'html':([0,7,17,],[6,10,19,]),'tagname':([1,],[9,]),'tagargs':([9,11,],[13,14,]),'elt':([0,7,17,],[7,7,7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> html","S'",1,None,None,None),
  ('html -> elt html','html',2,'p_html','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',21),
  ('html -> <empty>','html',0,'p_html_empty','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',25),
  ('elt -> WORD','elt',1,'p_elt_word','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',29),
  ('elt -> EQUAL','elt',1,'p_elt_word_eq','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',33),
  ('elt -> STRING','elt',1,'p_elt_word_string','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',37),
  ('tagname -> WORD','tagname',1,'p_tagname','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',41),
  ('tagnameend -> WORD','tagnameend',1,'p_tagnameend','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',47),
  ('elt -> LANGLE tagname tagargs SLASHRANGLE','elt',4,'p_elt_tag_empty','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',56),
  ('elt -> LANGLE tagname tagargs RANGLE html LANGLESLASH tagnameend RANGLE','elt',8,'p_elt_tag','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',67),
  ('tagargs -> <empty>','tagargs',0,'p_tagargs_empty','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',71),
  ('tagargs -> tagarg tagargs','tagargs',2,'p_tagargs','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',75),
  ('tagarg -> WORD EQUAL STRING','tagarg',3,'p_tagarg','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',79),
  ('elt -> JAVASCRIPT','elt',1,'p_elt_javascript','C:\\Users\\TRINITI\\Desktop\\web browser\\htmlgrammar.py',83),
]
